services:
  - type: web
    name: chatters-api
    runtime: python
    plan: starter
    autoDeploy: true
    region: frankfurt
    buildCommand: (cd backend && bash build.sh)
    startCommand: (cd backend && uvicorn chat.asgi:application --host 0.0.0.0 --port $PORT)

  - type: redis
    name: chatters-messaging
    ipAllowList: []
    region: frankfurt
    plan: starter
    maxmemoryPolicy: allkeys-lru
  
  - type: web
    name: chatters-web
    runtime: static
    buildCommand: (cd frontend && npm install && npm run build-only)
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: chatters-prod
    region: frankfurt
    plan: basic-4gb
    databaseName: primary_chatters_db
    user: chatters_web