# Generated by Django 5.1.1 on 2025-01-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0006_alter_langauge_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='The Prompt used to ask the AI')),
                ('reply', models.TextField(verbose_name='The Reply from the AI')),
                ('approved', models.BooleanField(default=False, verbose_name='Whether this response is correct')),
                ('to_language', models.CharField(max_length=5, verbose_name='the target language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message', verbose_name='The message being translated')),
            ],
            options={
                'ordering': ('approved', 'created_at', 'modified_at'),
            },
        ),
    ]
