/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LangSelector: typeof import('./components/LangSelector.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RoomsNavDrawer: typeof import('./components/RoomsNavDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
  }
}
