# Generated by Django 5.1.1 on 2024-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='translations',
            field=models.JSONField(default=dict, verbose_name='Translations'),
        ),
    ]
