# Generated by Django 5.1.1 on 2024-12-19 10:01
from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.conf import settings

def add_default_langs(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Language = apps.get_model('messaging', 'Langauge')
    langs = settings.SUPPORTED_LANGUAGES
    
    for lang in langs:
        Language.objects.create(code= lang[0], name=lang[1])
    
class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_langauge'),
    ]

    operations = [
        migrations.RunPython(add_default_langs)
    ]
