# Generated by Django 5.1.1 on 2024-12-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20241219_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langauge',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='The id of the Language'),
        ),
    ]
